CREATE TABLE STUDENT_T (
 STUDENT_NUMBER VARCHAR2(1000BYTE) NOT NULL PRIMARY KEY,
 STUDENT_NAME VARCHAR2(1000BYTE) NOT NULL,
 STUDENT_GRADE VARCHAR2(100BYTE) NOT NULL,
 STUDENT_CLASS VARCHAR2(100BYTE) NOT NULL,
 STUDENT_NO VARCHAR2(100BYTE) NOT NULL
 );
 
 CREATE TABLE SUBJECT_T (
 SUBJECT_"SUB.NO" VARCHAR2(100BYTE) NOT NULL PRIMARY KEY,
 SUBJUCT_SUB VARCHAR2(1000BYTE) NOT NULL
 );
 
 CREATE TABLE ENRO_T(
 ENRO_NUMBER VARCHAR2 REFERENCES STUDENT_T(STUNDENT_NUMBER),
 ENRO_"SUB.NO" VARCHAR2 REFERENCES SUBJECT_T(SUBJECT_"SUB.NO")
 )
 ;
 
 